In [13]:
import pickle
import numpy as np

In [14]:
ohe_sex = pickle.load(open("models/ohe_sex.pkl", "rb"))
ohe_embarked = pickle.load(open("models/ohe_embarked.pkl", "rb"))
clf = pickle.load( open("models/clf.pkl", "rb"))

c:\Users\Dell\Downloads\Learning Data Science\.venv\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 1.7.2 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\Dell\Downloads\Learning Data Science\.venv\Lib\site-packages\sklearn\base.py:463: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.7.2 when using version 1.8.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [15]:
# Assume user input 
#Pclass/gender/age/Sibsp/Parch/Fare/Embarkedabs
test_input = np.array([2,'male',31.0,0,0,10.5,'5'],dtype=object).reshape(1,7)

In [16]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, '5']], dtype=object)

In [17]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\Dell\Downloads\Learning Data Science\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [18]:
test_input_sex

array([[0., 1.]])

In [19]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

c:\Users\Dell\Downloads\Learning Data Science\.venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [20]:
test_input_embarked

array([[0., 0., 0., 0.]])

In [21]:
test_input_age = test_input[:,2].reshape(1,1)

In [22]:
test_input_age

array([[31.0]], dtype=object)

In [24]:
test_input_transform = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [26]:
test_input_transform.shape

(1, 11)

In [ ]:
clf.predict(test_input_transform) 
# 0 is define that the man/women - dead
# 1 is define that the man/women - Alive


array([0])