#### Spam Ham Classification Project using NLTK and BOW,TF-IDF

##### Bow, TF-IDF, Machine learning Algorithms

1. Preprocessing and Cleaning
2. Train Test Split
3. Bow and TF-IDF (Sentences --> Vectors) {Preventing Data Leakage}
4. Trained Our Models

In [181]:
import pandas as pd
import numpy as np

In [182]:
messages = pd.read_csv("SMSSpamCollection.txt", sep="\t", names=['label','message'])

In [183]:
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [184]:
# Data Cleaning and Preprocessing
import re # Regular expresion
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [185]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [186]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [187]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

### Create Bag of words

In [188]:
## Output Features
y = pd.get_dummies(messages['label'])
y = y.iloc[:,0].values

In [189]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_test,y_test = train_test_split(corpus,y,test_size=0.2,random_state=42)

In [190]:
# Create the Bag Of Words Model 
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500,ngram_range=(1,2))

In [191]:
len(X_train),len(y)

(4457, 5572)

In [192]:
# Independent feature 
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [193]:
np.set_printoptions(edgeitems=30,linewidth=100000,
                    formatter=dict(float=lambda x: "%.3g" % x))

X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [194]:
cv.vocabulary_

{'repli': np.int64(1716),
 'win': np.int64(2396),
 'weekli': np.int64(2370),
 'world': np.int64(2431),
 'cup': np.int64(456),
 'send': np.int64(1819),
 'stop': np.int64(1985),
 'end': np.int64(586),
 'servic': np.int64(1835),
 'send stop': np.int64(1825),
 'stop end': np.int64(1987),
 'hello': np.int64(907),
 'sort': np.int64(1936),
 'town': np.int64(2179),
 'alreadi': np.int64(49),
 'dont': np.int64(540),
 'rush': np.int64(1762),
 'home': np.int64(943),
 'eat': np.int64(573),
 'let': np.int64(1136),
 'know': np.int64(1080),
 'let know': np.int64(1138),
 'come': np.int64(380),
 'go': np.int64(787),
 'tell': np.int64(2070),
 'told': np.int64(2156),
 'hey': np.int64(910),
 'till': np.int64(2133),
 'dint': np.int64(525),
 'meet': np.int64(1269),
 'even': np.int64(612),
 'singl': np.int64(1877),
 'time': np.int64(2134),
 'saw': np.int64(1783),
 'situat': np.int64(1885),
 'orang': np.int64(1497),
 'bring': np.int64(214),
 'rington': np.int64(1742),
 'free': np.int64(705),
 'hit': np.int64(9

In [195]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB()

In [196]:
spam_detect_model.fit(X_train,y_train)

,"alpha alpha: float or array-like of shape (n_features,), default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None


In [197]:
y_pred = spam_detect_model.predict(X_test)

In [198]:
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1], shape=(1115,))

In [199]:
# compar y_test & y_pred 
from sklearn.metrics import accuracy_score,classification_report

In [200]:
accuracy_score(y_test,y_pred)

0.8780269058295964

In [201]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.70      0.15      0.25       149
        True       0.88      0.99      0.93       966

    accuracy                           0.88      1115
   macro avg       0.79      0.57      0.59      1115
weighted avg       0.86      0.88      0.84      1115



### Create The TF-IDF Model 

In [212]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_test,y_test = train_test_split(corpus,y,test_size=0.2)

In [213]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X_train = tv.fit_transform(X_train).toarray()
X_test = tv.transform(X_test).toarray()


In [214]:
X_train

array([[0, 0, 0.409, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 

In [215]:
tv.vocabulary_

{'pl': np.int64(1574),
 'go': np.int64(799),
 'ahead': np.int64(35),
 'want': np.int64(2331),
 'sure': np.int64(2034),
 'great': np.int64(859),
 'weekend': np.int64(2371),
 'abiola': np.int64(2),
 'great weekend': np.int64(861),
 'haha': np.int64(895),
 'thinkin': np.int64(2106),
 'call': np.int64(247),
 'messag': np.int64(1279),
 'miss': np.int64(1306),
 'miss call': np.int64(1308),
 'good': np.int64(833),
 'even': np.int64(617),
 'ttyl': np.int64(2193),
 'good even': np.int64(838),
 'turn': np.int64(2196),
 'phone': np.int64(1555),
 'mom': np.int64(1332),
 'tell': np.int64(2067),
 'everyon': np.int64(626),
 'cancer': np.int64(286),
 'sister': np.int64(1888),
 'stop': np.int64(1991),
 'hurt': np.int64(994),
 'talk': np.int64(2053),
 'put': np.int64(1657),
 'see': np.int64(1808),
 'get': np.int64(772),
 'home': np.int64(961),
 'love': np.int64(1196),
 'get home': np.int64(777),
 'need': np.int64(1392),
 'stand': np.int64(1972),
 'away': np.int64(127),
 'heart': np.int64(919),
 'without

In [216]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_detect_model = MultinomialNB().fit(X_train,y_train)

In [217]:
# Prediction 
y_pred = spam_tfidf_detect_model.predict(X_test)

In [218]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], shape=(1115,))

In [219]:
score = accuracy_score(y_test,y_pred)
print(score)

0.862780269058296


In [220]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.02      0.60      0.04         5
           1       1.00      0.86      0.93      1110

    accuracy                           0.86      1115
   macro avg       0.51      0.73      0.48      1115
weighted avg       0.99      0.86      0.92      1115

