In [147]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

In [148]:
## Sentence 
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [149]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [150]:
""" 
Principal Component Analysis (PCA) for visualizing word vectors. It shows how similar words tend to cluster together in vector space, which is significant for applications like recommendation systems.
"""

' \nPrincipal Component Analysis (PCA) for visualizing word vectors. It shows how similar words tend to cluster together in vector space, which is significant for applications like recommendation systems.\n'

In [151]:
## Define the vocubulary size 
voc_size = 10000

In [152]:
## One Hot Representation

""" One-Hot Representation: where each word in a sentence is converted into a vector according to its index in a predefined vocabulary size (set at 10,000 in this case). Examples of sentences are provided to illustrate how each word is represented as a vector based on these indices."""


one_hot_rep = [one_hot(words,voc_size) for words in sent] # List comprehension
one_hot_rep

[[5257, 4134, 8141, 8940],
 [5257, 4134, 8141, 4120],
 [5257, 59, 8141, 5666],
 [6085, 1716, 6902, 5045, 3844],
 [6085, 1716, 6902, 5045, 3639],
 [6465, 5257, 7074, 8141, 5057],
 [5719, 4626, 436, 5045]]

In [153]:
import numpy as np
import pandas as pd 

In [154]:
""" 
Padding Sequences: To handle variance in sentence lengths, the instructor discusses the importance of padding sequences by adding zeros to ensure all sentences are of uniform length. This step is crucial for effective model training. 
"""
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen = sent_length)
print(embedded_docs)
# there the 2 'pre'-place zero before and 'post'- place after 

[[   0    0    0    0 5257 4134 8141 8940]
 [   0    0    0    0 5257 4134 8141 4120]
 [   0    0    0    0 5257   59 8141 5666]
 [   0    0    0 6085 1716 6902 5045 3844]
 [   0    0    0 6085 1716 6902 5045 3639]
 [   0    0    0 6465 5257 7074 8141 5057]
 [   0    0    0    0 5719 4626  436 5045]]


In [155]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [156]:
# Feature Representation
dim = 10  # Dimensions

In [157]:
from tensorflow.keras import Input

model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, dim))
model.compile(optimizer='adam', loss='mse')
model.summary()


Model: "sequential_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_15 (Embedding)        │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [158]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


array([[[-0.04264959, -0.02800393,  0.04453975, -0.04471982,
         -0.04162682,  0.01488977, -0.02855164, -0.00515113,
         -0.04737897, -0.04864285],
        [-0.04264959, -0.02800393,  0.04453975, -0.04471982,
         -0.04162682,  0.01488977, -0.02855164, -0.00515113,
         -0.04737897, -0.04864285],
        [-0.04264959, -0.02800393,  0.04453975, -0.04471982,
         -0.04162682,  0.01488977, -0.02855164, -0.00515113,
         -0.04737897, -0.04864285],
        [-0.04264959, -0.02800393,  0.04453975, -0.04471982,
         -0.04162682,  0.01488977, -0.02855164, -0.00515113,
         -0.04737897, -0.04864285],
        [-0.01495181,  0.01899118,  0.02151943,  0.0258724 ,
          0.0189043 , -0.04810632,  0.02752108,  0.00698266,
          0.00873693, -0.01797885],
        [ 0.01787634,  0.01437584,  0.02689841, -0.02086293,
          0.00751501,  0.04395885,  0.01733715,  0.03442911,
          0.04232102,  0.01609423],
        [-0.02076323, -0.00689821, -0.03327216, -0.0

In [159]:
embedded_docs[0] #First Sentence


array([   0,    0,    0,    0, 5257, 4134, 8141, 8940], dtype=int32)